version: '2'
services:
  sqlserver:
    image: microsoft/mssql-server-linux:2017-latest
    hostname: 'sqlserver'
    environment:
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: Uva123456@
      MSSQL_PID: Developer
    ports:
    - '1433:1433'

  trufas:
    image: carioca:latest
    hostname: 'carioca'
    network_mode: "host"
    ports:
    - '8081:8081'
    depends_on:
    - "sqlserver"